version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      routine-actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: swift
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
